name: Preview Dev Deployment

on:
  pull_request:
    branches:
      - master
      - dev

env:
  V: '1'

concurrency:
  group: tests
  cancel-in-progress: false

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Lint api
        run: |
          set -e
          make lint-api
      - name: Typecheck api
        run: |
          set -e
          make typecheck-api
      - name: Test api
        run: |
          make test-api
      - name: Lint chatbot
        run: |
          set -e
          make lint-chatbot
      - name: Typecheck chatbot
        run: |
          set -e
          make typecheck-chatbot
      - name: Test chatbot
        run: |
          make test-chatbot
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/mono_frontend/package.json
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend/mono_frontend
      - name: Run frontend tests
        run: npm test
        working-directory: ./frontend/mono_frontend
